### ISSUE TITLE
Versioned loads

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-resource-loader#32]
We should be able to load scripts versioned. @timomayer could you provide a example syntax, what you have thought about.

**Comment by jurekbarth** [comment]
@SheepFromHeaven can we rely on how npm does it? So something like `abc/slider.js@^4.4.1`

**Comment by SheepFromHeaven** [comment]
@jurekbarth  I agree there, but I personally don't know if that's all of the feature that @timomayer had in mind

**Comment by tiagomapmarques** [comment]
@timomayer, any updates on this issue?

**Comment by timomayer** [comment]
Sorry for not seeing this. Yes Jurek I thought about doing it exactly the way npm is doing it for example a path like static.client.com/biotopeComponent/^1.1.4 should load static.client.com/componentName/1.1.5 if available. The question to solve is how to get the "is available" information? Think we have to generate a kind of "index file" where all available versions are listed and the resource ladder can read out of this list what version to load

**Comment by jurekbarth** [comment]
@timomayer wouldn't that be an overhead? Couldn't we fix that on the serverside?

**Comment by timomayer** [comment]
the only way i see to solve it serverside is that we build something like a "biotope deployment tool" which helps us to deploy to CDNs into different folders so something like static.customer.com/bioComponent/1.1.1 for the actual version and also static.customer.com/bioComponent/1.1.x. When the components gets another version we deploy static.customer.com/bioComponent/1.1.2 and the same version overwrites static.customer.com/bioComponent/1.1.x than we need in frontend only change pathes from static.client.com/biotopeComponent/^1.1.1 to static.client.com/biotopeComponent/1.1.x to get the correct version. but this would probably lead into chaching issues.
More advanced things n the backend are not possible because we should aim for make it work on a static CDN storage without any logic options.

**Comment by timomayer** [comment]
has not to be built into the conditional loader, we ll solve this with https://www.npmjs.com/package/unpkg-server

**Comment by ctmm** [comment]
@timomayer @SheepFromHeaven  If this is not to be built on the resource loader can we close this issue?
