### ISSUE TITLE
URL validation regex leads to Catastrophic Backtracking

### ISSUE THREAD

**Issue by no-creative-name** [biotope/biotope-resource-loader#92]
The regex that's used in isHtmlFilePath needs to be altered ASAP, since for some URLs(e.g. https://feature-web.dev.xyzasd.ljl.com/) this leads to Catastrophic Backtracking that may crash the whole page.

**Comment by ctmm** [comment]
@no-creative-name @timomayer
The issue seems to have been fixed before ever being opened.

It was fixed on #88, although tests were never added to check for html files on multiple subdomains.
There is also an open #95 with exactly the same fixes.
I couldn't detect any other edge cases where `isHtmlFilePath` would break.

Would adding better test coverage suffice for closing it?

IE:
```
test('returns true html in path', () => {
  const isHtml = isHtmlFilePath('http://feature-web.dev.domain.origin.com:8080/sub/path/file.html');
  expect(isHtml).toBe(true);
});
```

Thank you!
